### ISSUE TITLE
cannot find ceil and floor pipe

### ISSUE THREAD

**Issue by tushar-1health** [a8m/ng-pipes#15]
Hello,

I tried using ceil pipe. I believe you haven't released the latest release on npm.

**Comment by a8m** [comment]
hi @tushar-1health 
I planned to publish a new version today. new version published.

feel free to open if you still have an issue with that. thanks

**Comment by tushar-1health** [comment]
Found peer TypeScript 2.0.10
node_modules/ng-pipes/src/collection/reverse.pipe.ts(8,20): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.

node_modules/ng-pipes/src/utils/utils.ts(39,13): error TS2339: Property 'repeat' does not exist on type 'string'.

**Comment by SteveVanOpstal** [comment]
ng-pipes depends on TypeScript 2.1.4 or higher. Updating TypeScript might do the trick

**Comment by tushar-1health** [comment]
@SteveVanOpstal 
```
Found peer TypeScript 2.1.6
node_modules/ng-pipes/src/collection/reverse.pipe.ts(8,20): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.

node_modules/ng-pipes/src/utils/utils.ts(39,13): error TS2339: Property 'repeat' does not exist on type 'string'.
```

**Comment by SteveVanOpstal** [comment]
@tushar-1health The project where you use `ng-pipes`, is it open source project? If so can you send me a link to it?

**Comment by tushar-1health** [comment]
@SteveVanOpstal Nop. Its a closed source. But I can help you debug this. Do let me know.

**Comment by SteveVanOpstal** [comment]
Angular (and therefore ng-pipes) relies on core-js to provide ES5 polyfills. Is it possible that you didn't add a core-js type definition (`@types/core-js`)?
