### ISSUE TITLE
how to filterBy collection instead of one search string

### ISSUE THREAD

**Issue by pukuotas** [a8m/ng-pipes#17]
hy, is it possible to filterBy the collection instead of one string? I`m talking about the third parameter in the form of [filterBy:properties:search:strict]. I want to extract objects by several id, e.x. I have objects with ids 1,2,3,4,5,6 and my visitor may select only several ids to see, say, 4,5,6.  So, how to get only the objects by selected several id numbers?

**Comment by mnewmedia** [comment]
Something like the filterFilter from `angularjs`? 
I think the`where` filter does something like that, but because the docs are not really docs, I found it by reading the [test](https://github.com/a8m/ng-pipes/blob/master/test/collection/where.pipe.spec.ts) of the `where pipe`.
