### ISSUE TITLE
Omit in Array

### ISSUE THREAD

**Issue by marcogrieco** [a8m/ng-pipes#18]
Hi,
i would like use omit filter for array but i have problems when i pass the method of my class that must filter the array

This is the html code
*ngFor="let p of pages | omit: omitItem"

This is the method of my class
omitItem(page) {
}

I have compilation errors.

Why? There are no examples about ng-pipes with arrays and custom methods.

Thanks.

**Comment by SteveVanOpstal** [comment]
Please add more information about the issue. You can use [StackBlitz](https://stackblitz.com/edit/angular-vyemuc) to create a minimal reproduction of the problem.
