### ISSUE TITLE
Ng-pipes is not available as a built module

### ISSUE THREAD

**Issue by SteveVanOpstal** [a8m/ng-pipes#4]
### Current Behaviour
[UNPKG](https://unpkg.com) currently does not provide a module, but the index file:
https://unpkg.com/ng-pipes

> unpkg is a fast, global content delivery network for stuff that is published to npm. 

### Desired Behaviour
A module can be made available so the user doesn't need to bundle `ng-pipes` it into their own code.

### Extra information
1. build `ng-pipes` into a module ([UMD](https://github.com/umdjs/umd))
2. minify it (optional)
3. add it to git in a `./dist` or `./build` folder
4. add the location of the module to the `main` parameter of `package.json`:
```
{
...
  "main": "build/ng-pipes[.min].js",
...
}
```

**Comment by a8m** [comment]
Thanks for your feedback @SteveVanOpstal 
Would you mind to do a pull request?

**Comment by SteveVanOpstal** [comment]
I can definitely do that, but what bundling/packaging technology did you have in mind?
I mainly work with [webpack](https://github.com/webpack/webpack) but if you prefer something else I probably can probably set that up too.

**Comment by a8m** [comment]
I don't have any preferences. webpack sounds good.
