### ISSUE TITLE
Ivy compatability

### ISSUE THREAD

**Issue by SlimenTN** [a8m/ng-pipes#62]
I'm using ng-pipe and recently I have upgraded my project to angular 18 but I get this error 
```
NgPipesModule' does not appear to be an NgModule class.
This likely means that the library (ng-pipes) which declares NgPipesModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```
Any idea about this?

**Comment by SteveVanOpstal** [comment]
This project is abandoned, https://github.com/fknop/angular-pipes is also not maintained but still works for Ivy I think

**Comment by SlimenTN** [comment]
thanks for your reply, then why I get the above error?

**Comment by SlimenTN** [comment]
@SteveVanOpstal thanks for your suggestion
